name: Istiak Bin mahmod
url: istiakbinmahmod.github.io
# permalink: /:title/
# baseurl: https://kylieying.com
# baseurl: ""
permalink: /blog/:title

# seo tag
plugins:
  - jekyll-seo-tag

collections:
  projects:
    output: true

# Google Analytics
google_analytics: G-TEEDE1GB8S
